ALTER TABLE "Conversation"
ADD COLUMN "isMuted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "muteExpiration" TIMESTAMP(3),
ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "isPinned" BOOLEAN NOT NULL DEFAULT false;
